name: Android Studio Plugin

on:
  push:
    tags:
    - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    # - uses: mxschmitt/action-tmate@v2    
    - name: Compile
      run: |
        set -o pipefail
        env
        sh get-idea-ic.sh
        PLUGIN_VERSION="$(echo $GITHUB_REF | sed 's,refs/tags/,,g')"
        sed -i -- "s/{{PLUGIN_VERSION}}/$PLUGIN_VERSION/g" META-INF/plugin.xml
        ant -v all
    - name: Upload Release Asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: TestFairyAndroidStudioPlugin.zip
        asset_name: testfairy-intellij-${{ github.ref }}-bin.zip

