name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Compile
        run: |
          echo "TF_PLUGIN_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          export TF_PLUGIN_VERSION=${GITHUB_REF#refs/*/}

          sed -i "s/{{REPLACEME}}/TF_PLUGIN_VERSION/g" META-INF/plugin.xml
          cat META-INF/plugin.xml

          bash scripts/build.sh
      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: TestFairyAndroidStudioPlugin.zip
          asset_name: testfairy-intellij-${{ github.ref }}-bin.zip

#      - name: Publish
#        run: |
#          ${{ env.TF_GRADLE_VERSION }}
#          curl -i --header "Authorization: Bearer <permanentToken>" -F pluginId=<pluginId> -F file=@<path to plugin .jar/.zip file> -F channel=<channel> https://plugins.jetbrains.com/plugin/uploadPlugin

